"""TiGrIS - Tiled Graph Inference Scheduler"""

try:
    from tigris._version import version as __version__
except ModuleNotFoundError:  # generated by setuptools-scm during install/build
    __version__ = "0+unknown"

SCHEMA_VERSION = 9
SCHEMA_VERSION_MIN = 2
SCHEMA_VERSION_TILE_AXIS = 5
SCHEMA_VERSION_STAGE_TABLE_AUTHORITY = 5
# A model input or output carries the dtype the model file declares for it,
# so the runtime can present the interface the model states rather than the
# encoding the plan happens to execute on.
SCHEMA_VERSION_INTERFACE_DTYPE = 6
SCHEMA_VERSION_TENSOR_LAYOUT = 7
# The loader refuses an operator attribute whose type it does not know, so a
# new attribute kind is a compatibility break rather than an additive change.
# Schema 8 therefore declares every kind this generation will carry at once,
# and each is validated on load whether or not an operator uses it yet, so the
# operators behind them can land one at a time without a further bump.
SCHEMA_VERSION_OP_ATTRIBUTE_KINDS = 8
SCHEMA_VERSION_BINARY_REQUANT = 9
SUPPORTED_SCHEMA_VERSIONS = tuple(range(SCHEMA_VERSION_MIN, SCHEMA_VERSION + 1))

TILE_AXIS_NONE = 0
TILE_AXIS_HEIGHT_OR_LENGTH = 1
TILE_AXIS_WIDTH = 2
TILE_AXIS_HW = 3

__all__ = [
    "__version__",
    "SCHEMA_VERSION",
    "SCHEMA_VERSION_MIN",
    "SCHEMA_VERSION_TILE_AXIS",
    "SCHEMA_VERSION_STAGE_TABLE_AUTHORITY",
    "SCHEMA_VERSION_INTERFACE_DTYPE",
    "SCHEMA_VERSION_BINARY_REQUANT",
    "SCHEMA_VERSION_OP_ATTRIBUTE_KINDS",
    "SCHEMA_VERSION_TENSOR_LAYOUT",
    "SUPPORTED_SCHEMA_VERSIONS",
    "TILE_AXIS_NONE",
    "TILE_AXIS_HEIGHT_OR_LENGTH",
    "TILE_AXIS_WIDTH",
    "TILE_AXIS_HW",
]
