"""TiGrIS - Tiled Graph Inference Scheduler"""

try:
    from tigris._version import version as __version__
except ModuleNotFoundError:  # generated by setuptools-scm during install/build
    __version__ = "0+unknown"

SCHEMA_VERSION = 4
SCHEMA_VERSION_MIN = 2
SUPPORTED_SCHEMA_VERSIONS = tuple(range(SCHEMA_VERSION_MIN, SCHEMA_VERSION + 1))

__all__ = [
    "__version__",
    "SCHEMA_VERSION",
    "SCHEMA_VERSION_MIN",
    "SUPPORTED_SCHEMA_VERSIONS",
]
