"""TiGrIS - Tiled Graph Inference Scheduler"""

try:
    from tigris._version import version as __version__
except ModuleNotFoundError:  # generated by setuptools-scm during install/build
    __version__ = "0+unknown"

SCHEMA_VERSION = 4

__all__ = ["__version__", "SCHEMA_VERSION"]
